/* Struktur*/

-- Tabelle BERICHT
DROP TABLE "SCOTT"."BERICHT";
CREATE TABLE "SCOTT"."BERICHT" (
  "B_NR" NUMBER(10) NOT NULL, 
  "B_NAME" VARCHAR2(50) NOT NULL,
  "B_WURZEL" "SYS"."XMLTYPE" NOT NULL, 
  CONSTRAINT "B_Schluessel" PRIMARY KEY("B_NR")); 

-- Tabelle XMLPAKET
DROP TABLE "SCOTT"."XMLPAKET";
CREATE TABLE "SCOTT"."XMLPAKET" (
  "X_NR" NUMBER(10) NOT NULL,
  "X_XMLSCHEMA" "SYS"."XMLTYPE" NOT NULL,
  "X_XSLT" "SYS"."XMLTYPE" NOT NULL, 
  CONSTRAINT "X_Schluessel" PRIMARY KEY("X_NR"));
 
-- Tabelle BERICHT_ZU_XMLPAKET
DROP TABLE "SCOTT"."BERICHT_ZU_XMLPAKET";
CREATE TABLE "SCOTT"."BERICHT_ZU_XMLPAKET" (
  "BZX_NR" NUMBER(10) NOT NULL,
  "B_NR" NUMBER(10) NOT NULL,
  "X_NR" NUMBER(10) NOT NULL, 
  CONSTRAINT "BZX_Schluessel" PRIMARY KEY("BZX_NR"));

